# This is a basic workflow to help you get started with Actions

name: solo

on:
  pull_request:
    types:
      - labeled     # a label is assigned 
      - unlabeled   # a label is removed (e.g. 'AT: WIP' is removed)
      - opened      # the PR is created
      - reopened    # a previously closed PR is reopened
      # - synchronize # the head branch is updated
    branches: 
      - develop # only run for PRs against develop

jobs:
  fail_if_wip:
    uses: ./.github/workflows/fail_if_wip.yml

  configure_build_test:
    needs: fail_if_wip
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
