# This is a basic workflow to help you get started with Actions

name: solo

# workflow runs whenever a PR against develop is opened or labeled
on:
  pull_request:
    types:
      - labeled
      - opened
    branches: 
      -develop


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  workflow-handler:
    runs-on: ubuntu-22.04
    steps:
    - name: Verification
      uses: actions/github-script@v6.4.0
      with:
        script: |
          const { execSync } = require("child_process");
          var response = execSync("curl -s -o /dev/null -w \"%{http_code}\" -H \"Accept: application/vnd.github+json\" -H \"Authorization: token ${{ secrets.CWPEARSON_CIDUMMY_METADATAREAD }}\"  -H \"X-GitHub-Api-Version: 2022-11-28\" https://api.github.com/repos/cwpearson/ci-dummy/collaborators/${{ github.actor }}")
          var status_code = response.toString()
          var valid_user = false
          if (status_code == "200") {
            valid_user = true
            console.log("user ${{ github.actor }} has started the workflow")
          }
 
          console.log("${{ github.event.action }}")
          if ("${{ github.event.action }}" === "opened" && valid_user) {
            console.log("starting job from pull request creation")
          }
          else if ("${{ github.event.action }}" === "labeled" && "${{ github.event.label.name }}" == "RUN AUTOTESTER" && valid_user) {
            console.log("starting job from label")
          }
          else {
            core.setFailed("not running job")
          }

  configure_build_test:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
