# This is a basic workflow to help you get started with Actions

name: solo

# What types of PR things cause this to run:
#   labeled:     a label is assigned 
#   unlaeled:    a label is removed
#   opened:      the PR is created
#   synchronize: the head branch is updated
#   reopened:    a previously closed PR is reopened
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened
    branches: 
      - develop

jobs:

  # Skip the action if the 'AT: WIP' label is attached
  check-wip:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.pull_request.labels.*.name, 'AT: WIP')"
    steps:
    - name: Verification
      run: |
        true
          

  configure_build_test:
    needs: check-wip
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
